name: test_graduation
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  awesome_notifications: 
  badges: null
  cached_network_image: 
  carousel_slider: null
  chewie: null
  cloud_firestore: 
  cloudinary_flutter: 
  cloudinary_public: 
  cloudinary_url_gen:
  connectivity_plus: 
  cupertino_icons: 
  dartz: null
  dio: 
  equatable: 
  fancy_shimmer_image: null
  firebase_auth: 
  firebase_core: 
  firebase_dynamic_links: 
  firebase_messaging: 
  fl_chart: 
  flutter:
    sdk: flutter
  flutter_bloc: 
  flutter_image_compress: 
  flutter_localization: 
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: 
  flutter_secure_storage: 
  flutter_spinkit: 
  flutter_svg: 
  geolocator: 
  get_it: 
  go_router:
  google_fonts: 
  google_maps_flutter: 
  google_sign_in: 
  iconly: 
  image_picker: 
  intl: 
  lottie: ^3.1.0
  modal_progress_hud_nsn: 
  path:
  pin_code_fields: 
  share_plus: 
  shared_preferences: 
  shimmer: 
  skeletonizer: 
  sliver_tools: 
  url_launcher:
  uuid: 
  very_good_analysis: 
  video_player: 
dev_dependencies:
  flutter_lints: ^6.0.0
  # 🔥 إضافة مكتبة الشاشة الافتتاحية
  flutter_native_splash: ^2.3.11
  flutter_test:
    sdk: flutter

# 🔥 إعدادات شاشة بيوت الاحترافية
flutter_native_splash:
  color: "#ffffff" # خلفية بيضاء نظيفة
  image: assets/images/logo.png # شعارك هنا
  android_12:
    image: assets/images/logo.png
    color: "#ffffff"
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/profile/
    - assets/images/bag/
    - assets/images/banners/
    - assets/images/categories/
    - assets/images/dashboard/
    - assets/lottie/
    - lang/ar.json
    - lang/en.json
