name: test_graduation
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  awesome_notifications: null
  badges: null
  cached_network_image: null
  carousel_slider: null
  chewie: null
  cloud_firestore: null
  cloudinary_flutter: null
  cloudinary_public: null
  cloudinary_url_gen: null
  connectivity_plus: null
  cupertino_icons: null
  dartz: null
  dio: null
  equatable: null
  fancy_shimmer_image: null
  firebase_auth: null
  firebase_core: null
  firebase_dynamic_links: null
  firebase_messaging: null
  fl_chart: null
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_dotenv: ^6.0.1
  flutter_localization: null
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: null
  flutter_secure_storage: null
  flutter_spinkit: null
  flutter_svg: null
  get_it: null
  go_router: null
  google_fonts: null
  google_sign_in: null
  googleapis_auth: ^2.3.2
  iconly: null
  image_picker: null
  intl: null
  lottie: ^3.1.0
  modal_progress_hud_nsn: null
  path: null
  pin_code_fields: null
  share_plus: null
  shared_preferences: null
  shimmer: null
  skeletonizer: null
  sliver_tools: null
  url_launcher: null
  uuid: null
  very_good_analysis: null
  video_player: null
dev_dependencies:
  flutter_lints: ^6.0.0
  # 🔥 إضافة مكتبة الشاشة الافتتاحية
  flutter_native_splash: ^2.3.11
  flutter_test:
    sdk: flutter

# 🔥 إعدادات شاشة بيوت الاحترافية
flutter_native_splash:
  color: "#ffffff" # خلفية بيضاء نظيفة
  image: assets/images/logo.png # شعارك هنا
  android_12:
    image: assets/images/logo.png
    color: "#ffffff"
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/profile/
    - assets/images/bag/
    - assets/images/banners/
    - assets/images/categories/
    - assets/images/dashboard/
    - assets/lottie/
    - lang/ar.json
    - lang/en.json
    - assets/.env
