// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNbFbYsPiVSYI3R09jqUfYtm0RNGA7gqU',
    appId: '1:692629357809:web:b31b4e75e4d4077dbed550',
    messagingSenderId: '692629357809',
    projectId: 'real-estate-541c5',
    authDomain: 'real-estate-541c5.firebaseapp.com',
    storageBucket: 'real-estate-541c5.firebasestorage.app',
    measurementId: 'G-SDPK8EYT2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY_mzpjJ7Fnik4HhBuhU3qf_cUS4kDlnU',
    appId: '1:692629357809:android:2a4cfb4feddd03e2bed550',
    messagingSenderId: '692629357809',
    projectId: 'real-estate-541c5',
    storageBucket: 'real-estate-541c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNt2vsbpUXfA8S2rXwQUebiSGL0FDLXsU',
    appId: '1:692629357809:ios:8eb73684082319fdbed550',
    messagingSenderId: '692629357809',
    projectId: 'real-estate-541c5',
    storageBucket: 'real-estate-541c5.firebasestorage.app',
    iosBundleId: 'com.example.testGraduation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNt2vsbpUXfA8S2rXwQUebiSGL0FDLXsU',
    appId: '1:692629357809:ios:8eb73684082319fdbed550',
    messagingSenderId: '692629357809',
    projectId: 'real-estate-541c5',
    storageBucket: 'real-estate-541c5.firebasestorage.app',
    iosBundleId: 'com.example.testGraduation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNbFbYsPiVSYI3R09jqUfYtm0RNGA7gqU',
    appId: '1:692629357809:web:9a11de268446f8ebbed550',
    messagingSenderId: '692629357809',
    projectId: 'real-estate-541c5',
    authDomain: 'real-estate-541c5.firebaseapp.com',
    storageBucket: 'real-estate-541c5.firebasestorage.app',
    measurementId: 'G-4F48YBNBZ2',
  );
}
