import 'package:cloud_firestore/cloud_firestore.dart';
import '../../features/my_properties/domain/entities/property_entity.dart';
import '../enums/property_enums.dart';

class PropertyModel extends PropertyEntity {
  const PropertyModel({
    required super.id,
    required super.title,
    required super.description,
    required super.type,
    required super.listingType,
    required super.price,
    required super.currency,
    required super.area,
    required super.createdAt,
    super.views,
    super.isFeatured,
    super.status,
    super.statusHistory,
    required super.images,
    required super.media,
    required super.facilities,
    required super.governorate,
    required super.city,
    required super.location,
    required super.phone,
    required super.whatsapp,
    super.email,
    required super.sellerId,
    required super.sellerName,
    super.sellerImage,
    super.sellerJoinDate,
    super.sellerRating,
    super.buildingAge,
    super.finishType,
    super.ownershipType,
    super.direction,
    super.isLicensed,
    super.hasInstallment,
    super.downPayment,
    super.monthlyInstallment,
    super.installmentDuration,
    super.installmentNotes,
    super.totalRooms,
    super.bedrooms,
    super.bathrooms,
    super.floorNumber,
    super.totalFloors,
    super.heatingType,
    super.landType,
    super.frontagesCount,
    super.streetWidth,
    super.farmType,
    super.irrigationType,
    super.crops,
    super.frontageWidth,
    super.shopLocation,
    super.commercialActivity,
    super.poolType,
    super.poolSize,
    super.examinationRooms,
    super.medicalEquipment,
    super.warehouseHeight,
    super.warehouseFloorType,
    super.hallCapacity,
    super.workshopType,
    super.workshopHeight,
  });

  factory PropertyModel.fromJson(Map<String, dynamic> json) {
    // معالجة التاريخ بمرونة (String أو Timestamp)
    DateTime parseDate(dynamic date) {
      if (date == null) return DateTime.now();
      if (date is Timestamp) return date.toDate();
      if (date is String) return DateTime.tryParse(date) ?? DateTime.now();
      return DateTime.now();
    }

    return PropertyModel(
      id: json['id'] as String? ?? '',
      title: json['title'] as String? ?? '',
      description: json['description'] as String? ?? '',
      type: PropertyType.values.firstWhere(
        (e) => e.name == json['type'],
        orElse: () => PropertyType.housesAndApartments,
      ),
      listingType: ListingType.values.firstWhere(
        (e) => e.name == json['listingType'],
        orElse: () => ListingType.sale,
      ),
      price: (json['price'] as num? ?? 0).toDouble(),
      currency: json['currency'] as String? ?? 'usd',
      area: (json['area'] as num? ?? 0).toDouble(),
      createdAt: parseDate(json['createdAt']),
      views: json['views'] as int? ?? 0,
      isFeatured: json['isFeatured'] as bool? ?? false,
      status: PropertyStatus.values.firstWhere(
        (e) => e.name == json['status'],
        orElse: () => PropertyStatus.active,
      ),
      statusHistory: (json['statusHistory'] as List?)
              ?.map((e) => Map<String, dynamic>.from(e as Map))
              .toList() ??
          const [],
      images: List<String>.from(json['images'] as List? ?? []),
      media: List<String>.from(json['media'] as List? ?? json['images'] as List? ?? []),
      facilities: List<String>.from(json['facilities'] as List? ?? []),
      governorate: json['governorate'] as String? ?? '',
      city: json['city'] as String? ?? '',
      location: json['location'] as String? ?? '',
      phone: json['phone'] as String? ?? '',
      whatsapp: json['whatsapp'] as String? ?? '',
      email: json['email'] as String?,
      sellerId: json['sellerId'] as String? ?? 'unknown',
      sellerName: json['sellerName'] as String? ?? 'user_label',
      sellerImage: json['sellerImage'] as String?,
      sellerJoinDate: json['sellerJoinDate'] as String? ?? 'new_member',
      sellerRating: (json['sellerRating'] as num? ?? 4.5).toDouble(),
      buildingAge: json['buildingAge'] as int?,
      finishType: json['finishType'] as String?,
      ownershipType: json['ownershipType'] as String?,
      direction: json['direction'] as String?,
      isLicensed: json['isLicensed'] as bool? ?? false,
      hasInstallment: json['hasInstallment'] as bool? ?? false,
      downPayment: (json['downPayment'] as num?)?.toDouble(),
      monthlyInstallment: (json['monthlyInstallment'] as num?)?.toDouble(),
      installmentDuration: json['installmentDuration'] as int?,
      installmentNotes: json['installmentNotes'] as String?,
      totalRooms: json['totalRooms'] as int?,
      bedrooms: json['bedrooms'] as int?,
      bathrooms: json['bathrooms'] as int?,
      floorNumber: json['floorNumber'] as int?,
      totalFloors: json['totalFloors'] as int?,
      heatingType: json['heatingType'] as String?,
      landType: json['landType'] as String?,
      frontagesCount: json['frontagesCount'] as int?,
      streetWidth: (json['streetWidth'] as num?)?.toDouble(),
      farmType: json['farmType'] as String?,
      irrigationType: json['irrigationType'] as String?,
      crops: json['crops'] as String?,
      frontageWidth: (json['frontageWidth'] as num?)?.toDouble(),
      shopLocation: json['shopLocation'] as String?,
      commercialActivity: json['commercialActivity'] as String?,
      poolType: json['poolType'] as String?,
      poolSize: json['poolSize'] as String?,
      examinationRooms: json['examinationRooms'] as int?,
      medicalEquipment: json['medicalEquipment'] as String?,
      warehouseHeight: (json['warehouseHeight'] as num?)?.toDouble(),
      warehouseFloorType: json['warehouseFloorType'] as String?,
      hallCapacity: json['hallCapacity'] as int?,
      workshopType: json['workshopType'] as String?,
      workshopHeight: (json['workshopHeight'] as num?)?.toDouble(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'type': type.name,
      'listingType': listingType.name,
      'price': price,
      'currency': currency,
      'area': area,
      'createdAt': createdAt.toIso8601String(),
      'views': views,
      'isFeatured': isFeatured,
      'status': status.name,
      'statusHistory': statusHistory,
      'images': images,
      'media': media,
      'facilities': facilities,
      'governorate': governorate,
      'city': city,
      'location': location,
      'phone': phone,
      'whatsapp': whatsapp,
      'email': email,
      'sellerId': sellerId,
      'sellerName': sellerName,
      'sellerImage': sellerImage,
      'sellerJoinDate': sellerJoinDate,
      'sellerRating': sellerRating,
      'buildingAge': buildingAge,
      'finishType': finishType,
      'ownershipType': ownershipType,
      'direction': direction,
      'isLicensed': isLicensed,
      'hasInstallment': hasInstallment,
      'downPayment': downPayment,
      'monthlyInstallment': monthlyInstallment,
      'installmentDuration': installmentDuration,
      'installmentNotes': installmentNotes,
      'totalRooms': totalRooms,
      'bedrooms': bedrooms,
      'bathrooms': bathrooms,
      'floorNumber': floorNumber,
      'totalFloors': totalFloors,
      'heatingType': heatingType,
      'landType': landType,
      'frontagesCount': frontagesCount,
      'streetWidth': streetWidth,
      'farmType': farmType,
      'irrigationType': irrigationType,
      'crops': crops,
      'frontageWidth': frontageWidth,
      'shopLocation': shopLocation,
      'commercialActivity': commercialActivity,
      'poolType': poolType,
      'poolSize': poolSize,
      'examinationRooms': examinationRooms,
      'medicalEquipment': medicalEquipment,
      'warehouseHeight': warehouseHeight,
      'warehouseFloorType': warehouseFloorType,
      'hallCapacity': hallCapacity,
      'workshopType': workshopType,
      'workshopHeight': workshopHeight,
    };
  }

  factory PropertyModel.fromEntity(PropertyEntity entity) {
    return PropertyModel(
      id: entity.id,
      title: entity.title,
      description: entity.description,
      type: entity.type,
      listingType: entity.listingType,
      price: entity.price,
      currency: entity.currency,
      area: entity.area,
      createdAt: entity.createdAt,
      views: entity.views,
      isFeatured: entity.isFeatured,
      status: entity.status,
      statusHistory: entity.statusHistory,
      images: entity.images,
      media: entity.media,
      facilities: entity.facilities,
      governorate: entity.governorate,
      city: entity.city,
      location: entity.location,
      phone: entity.phone,
      whatsapp: entity.whatsapp,
      email: entity.email,
      sellerId: entity.sellerId,
      sellerName: entity.sellerName,
      sellerImage: entity.sellerImage,
      sellerJoinDate: entity.sellerJoinDate,
      sellerRating: entity.sellerRating,
      buildingAge: entity.buildingAge,
      finishType: entity.finishType,
      ownershipType: entity.ownershipType,
      direction: entity.direction,
      isLicensed: entity.isLicensed,
      hasInstallment: entity.hasInstallment,
      downPayment: entity.downPayment,
      monthlyInstallment: entity.monthlyInstallment,
      installmentDuration: entity.installmentDuration,
      installmentNotes: entity.installmentNotes,
      totalRooms: entity.totalRooms,
      bedrooms: entity.bedrooms,
      bathrooms: entity.bathrooms,
      floorNumber: entity.floorNumber,
      totalFloors: entity.totalFloors,
      heatingType: entity.heatingType,
      landType: entity.landType,
      frontagesCount: entity.frontagesCount,
      streetWidth: entity.streetWidth,
      farmType: entity.farmType,
      irrigationType: entity.irrigationType,
      crops: entity.crops,
      frontageWidth: entity.frontageWidth,
      shopLocation: entity.shopLocation,
      commercialActivity: entity.commercialActivity,
      poolType: entity.poolType,
      poolSize: entity.poolSize,
      examinationRooms: entity.examinationRooms,
      medicalEquipment: entity.medicalEquipment,
      warehouseHeight: entity.warehouseHeight,
      warehouseFloorType: entity.warehouseFloorType,
      hallCapacity: entity.hallCapacity,
      workshopType: entity.workshopType,
      workshopHeight: entity.workshopHeight,
    );
  }

  PropertyEntity toEntity() {
    return PropertyEntity(
      id: id,
      title: title,
      description: description,
      type: type,
      listingType: listingType,
      price: price,
      currency: currency,
      area: area,
      createdAt: createdAt,
      views: views,
      isFeatured: isFeatured,
      status: status,
      statusHistory: statusHistory,
      images: images,
      media: media,
      facilities: facilities,
      governorate: governorate,
      city: city,
      location: location,
      phone: phone,
      whatsapp: whatsapp,
      email: email,
      sellerId: sellerId,
      sellerName: sellerName,
      sellerImage: sellerImage,
      sellerJoinDate: sellerJoinDate,
      sellerRating: sellerRating,
      buildingAge: buildingAge,
      finishType: finishType,
      ownershipType: ownershipType,
      direction: direction,
      isLicensed: isLicensed,
      hasInstallment: hasInstallment,
      downPayment: downPayment,
      monthlyInstallment: monthlyInstallment,
      installmentDuration: installmentDuration,
      installmentNotes: installmentNotes,
      totalRooms: totalRooms,
      bedrooms: bedrooms,
      bathrooms: bathrooms,
      floorNumber: floorNumber,
      totalFloors: totalFloors,
      heatingType: heatingType,
      landType: landType,
      frontagesCount: frontagesCount,
      streetWidth: streetWidth,
      farmType: farmType,
      irrigationType: irrigationType,
      crops: crops,
      frontageWidth: frontageWidth,
      shopLocation: shopLocation,
      commercialActivity: commercialActivity,
      poolType: poolType,
      poolSize: poolSize,
      examinationRooms: examinationRooms,
      medicalEquipment: medicalEquipment,
      warehouseHeight: warehouseHeight,
      warehouseFloorType: warehouseFloorType,
      hallCapacity: hallCapacity,
      workshopType: workshopType,
      workshopHeight: workshopHeight,
    );
  }
}
